version: '3.8'

services:
  marcus-server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://marcus-db:27017/marcus
    depends_on:
      - marcus-db
    volumes:
      - ./server/logs:/app/logs
    restart: unless-stopped

  marcus-client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - marcus-server
    restart: unless-stopped

  marcus-db:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=marcus
    volumes:
      - marcus_db_data:/data/db
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - marcus_redis_data:/data
    restart: unless-stopped

volumes:
  marcus_db_data:
  marcus_redis_data:
